Somentimes we need use a validation of a exception on code, using unit tests

```
Assert.Throws<TypeException>(() => method.than.callException(parameters...) );
```